
# Language/versions
language: node_js
node_js:
  - "4.0"
  - "0.12"
  - "0.10"

# Build only master (and pull-requests)
branches:
  only:
    - master

# Build script
script: make ci

# Notifications
notifications:
  slack: thefeds:vG3hLYB07EwTYpQFp3TNUx82
